config/routes.rb
EventStack::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register" }

  get "home/index"

  resources :users

  resources :majors

  resources :events do
    get :search, :on => :collection
  end

  root :to => 'home#index', as: 'home'

end

app/models/event.rb
class Event < ActiveRecord::Base

  searchable do 
    text :name, :boost => 5
    text :description, :location
    text :start_date, :when_tokenizer, :has_food
  end

  def start_date
    start_datetime.strftime("%a %A %d %B %Y") + " " + start_datetime.to_date.to_s
  end

  def when_tokenizer
    weekend = ["Fri", "Sat", "Sun"]

    when_token = ""
    
    when_token += "today " if start_datetime.to_date == Date.today
    when_token += "tomorrow " if start_datetime.to_date == Date.tomorrow
    when_token += "weekend "  if weekend.include? start_datetime.strftime("%a") and 
                                  start_datetime.to_date > Date.today
    when_token
  end

  def has_food
    "food" if food_provided == true
  end

  # ASSOCIATIONS
  belongs_to :creator, class_name: 'User', inverse_of: :created_events
  has_and_belongs_to_many :voters, class_name: 'User', join_table: :votes, foreign_key: :voted_event_id, association_foreign_key: :voter_id
  has_and_belongs_to_many :majors
  attr_accessible :description, :end_datetime, :food_provided, :location, :name, :start_datetime

  # VALIDATIONS
  validates :name, presence: true, allow_blank: false, length: { maximum: 40 }
  validates :description, presence: true, allow_blank: false, length: { maximum: 800 }

  # TODO: datetime validations
  # validates :start_datetime, presence: true, allow_blank: false
  # validates :end_datetime, presence: true, allow_blank: false
  # validates :string, presence: true, allow_blank: false

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  TITLES = [ "Here is what's going on!", "Stuff that is going to happen",
             "Your next party is...", "Where can you eat...",
             "Where can you meet new people...", "Where can you have fun?!",
             "What would you want to do?!", "Here is what we can offer!",
             "Pick your entertainment!", "Stuff you can go to",
             "Cool events!", "Fun events to go to!", "Are you not entertained?!" ]


  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @page_title = TITLES[rand(TITLES.length)]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    begin
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to show invalid event #{params[:id]}"
      redirect_to events_path, notice: 'Invalid event ID'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @event }
      end
    end
  end

  # GET /search
  # GET /search.json
  def search
    date = nil
    date = Date.strptime(params[:date], '%m/%d/%Y') if params[:date] != ""

    search =  Event.search do
                fulltext params[:search_text] if params[:search_text]
                fulltext date if date
              end

    @events = search.results
    if @events.count > 0
      @page_title = "Search Results for "
      @page_title += "'#{params[:search_text]}'" if params[:search_text] != ""
      @page_title += "'#{params[:date]}'" if params[:date] != ""
    else
      @page_title = "Sorry, no events were found!"
    end

    respond_to do |format|
      format.html { render :action => :index }
      format.json { render json: @events }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    begin
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to edit invalid event #{params[:id]}"
      redirect_to events_path, notice: 'Invalid event ID'
    else
      # given event was not created by the current user
      if (@event.creator.id != current_user.id) && (!current_user.admin?)
        logger.error "Attempt to edit invalid event #{params[:id]} with creator_id #{@event.creator.id} for current user_id #{current_user.id}"
        redirect_to events_path, notice: 'You do not have permission to edit that event!'
      end
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.creator = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    # given event was not created by the current user
    if (@event.creator.id != current_user.id) && (!current_user.admin?)
      logger.error "Attempt to update invalid event #{params[:id]} with creator_id #{@event.creator.id} for current user_id #{current_user.id}"      
      redirect_to events_path, notice: 'You do not have permission to update that event!'
    end

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    # check if admin
    begin
      @event = Event.find(params[:id])

      # If not admin and the event is not created by the current user
      if !current_user.admin? && (@event.creator.id != current_user.id)
        redirect_to events_path
      end

    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to show invalid event #{params[:id]}"
      redirect_to events_path, notice: 'Invalid event ID'
    else
      # given event was not created by the current user
      if (@event.creator.id != current_user.id) && (!current_user.admin?)
        logger.error "Attempt to delete invalid event #{params[:id]} with creator_id #{@event.creator.id} for current user_id #{current_user.id} and not admin"      
        redirect_to events_path, notice: 'You do not have permission to delete that event!'
      end
      @event.destroy

      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br />
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br />
    <%= f.datetime_select :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :food_provided %><br />
    <%= f.check_box :food_provided %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_show_event.html.erb
<% if !details %>
<a class="event_link" href="<%= event_path(event) %>">
<% end %>

<% if details %>
<span class= "event_single_entry">
<% else %>
<span class= "event_entry hover hoverable">
<% end %>

  <% if !details %>
    <p class= "event_name"> 
      <%= event.name %>
    </p>
  <% end %>

  <% if details %>
  <p>
    <b>Description:</b>
    <%= event.description %>
  </p>
  <% end %>

  <p>
    <b>Start datetime:</b>
    <%= event.start_datetime %>
  </p>

  <% if details %>
  <p>
    <b>End datetime:</b>
    <%= event.end_datetime %>
  </p>
  <% end %>

  <p>
    <b>Location:</b>
    <%= event.location %>
  </p>

  <p>
    <b>Food provided:</b>
      <% if event.food_provided %>
        <i class= "icon-food icon-3x"></i>
      <% end %>
  </p>

  <% if current_user %>
    <% if current_user.admin? || (event.creator.id == current_user.id) %>
      <%= link_to content_tag(:i, "", class: "icon-pencil"), edit_event_path(event), class: 'btn btn-search remove_fields' %>
      <%= link_to content_tag(:i, "", class: "icon-trash"), event, method: :delete, data: { confirm: 'Are you sure you want to delete this event?'}, class: 'btn btn-danger remove_fields' %>
    <% end %>
  <% end %>
  <% if details %>
    <%= link_to 'Back', events_path, class: 'btn btn-inverse remove_fields' %>
  <% end %>
</span>

<% if !details %>
</a>
<% end %>

app/views/events/_show_events.html.erb
<% events.each do |event| %>
    <%= render 'events/show_event', event: event, details: false %>
<% end %>

app/views/events/edit.html.erb
<h1 id="page_title">Editing event</h1>

<span class="event_single_entry">
<%= render 'form' %>
</span>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if notice %>
    <p id="error_notice"><%= notice %></p>
<% end %>

<% if current_user %>
  <%= link_to 'New Event', new_event_path, class: 'new_button' %>
<% end %>


<h1 id="page_title"><%= @page_title %></h1>

<%= render 'show_events', events: @events %>
<br />

app/views/events/new.html.erb
<h1 id="page_title">New event</h1>

<span class="event_single_entry">
<%= render 'form' %>
</span>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<table class= "title_table">
  <col width="700">
  <tr>
    <td> 
      <h2 id="page_title"><%= @event.name %></h2>
      <h3 id="event_creator_title"><span id="by_element">by</span> <%= @event.creator.username %></h3>
    </td>
    <td> 
      <i class= "icon-food icon-3x <%= @event.food_provided ? 'icon-green' : 'icon-red' %>"></i>
    </td>
  </tr>
</table>
<%= render 'show_event', event: @event, details: true %>