config/routes.rb
EventStack::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register" }

  get "home/index"

  resources :users

  resources :majors

  resources :events do
    get :search, :on => :collection
  end

  root :to => 'home#index', as: 'home'

end

app/models/major.rb
class Major < ActiveRecord::Base
  
  # ASSOCIATIONS
  has_and_belongs_to_many :users 
  has_and_belongs_to_many :events

  attr_accessible :name

  # VALIDATIONS
  validates :name, presence: true, allow_blank: false, length: { maximum: 50 }

end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  # TODO: consider using CanCan for roles!
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @majors }
    end
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
    begin
      @major = Major.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to show invalid major #{params[:id]}"
      redirect_to majors_path, notice: 'Invalid major ID'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @major }
      end
    end
  end

  # GET /majors/new
  # GET /majors/new.json
  def new
    @major = Major.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @major }
    end
  end

  # GET /majors/1/edit
  def edit
    begin
      @major = Major.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to show invalid major #{params[:id]}"
      redirect_to users_path, notice: 'Invalid major ID'
    end
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(params[:major])

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render json: @major, status: :created, location: @major }
      else
        format.html { render action: "new" }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /majors/1
  # PUT /majors/1.json
  def update
    begin
      @major = Major.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to update invalid major #{params[:id]}"
      redirect_to majors_path, notice: 'Invalid major ID'
    else
      respond_to do |format|
        if @major.update_attributes(params[:major])
          format.html { redirect_to @major, notice: 'Major was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @major.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    begin
      @major = Major.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to delete invalid major #{params[:id]}"
      redirect_to majors_path, notice: 'Invalid major ID'
    else
      @major.destroy

      respond_to do |format|
        format.html { redirect_to majors_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.erb
<%= form_for(@major) do |f| %>
  <% if @major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
      <% @major.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/majors/edit.html.erb
<h1>Editing major</h1>

<%= render 'form' %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<h1 id="page_title">Listing majors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @majors.each do |major| %>
  <tr>
    <td><%= major.name %></td>
    <td><%= link_to 'Show', major, class: 'btn btn-inverse remove_fields' %></td>
    <td><%= link_to content_tag(:i, "", class: "icon-pencil"), edit_major_path(major), class: 'btn btn-search remove_fields' %></td>
    <td><%= link_to content_tag(:i, "", class: "icon-trash"), major, method: :delete, data: { confirm: 'Are you sure you want to delete this major?'}, class: 'btn btn-danger remove_fields' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<h1>New major</h1>

<%= render 'form' %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <b>Name:</b>
  <%= @major.name %>
</p>

<%= link_to content_tag(:i, " Edit Major", class: "icon-pencil"), edit_major_path(@major), class: 'btn btn-search remove_fields' %>
<%= link_to 'Back', majors_path, class: 'btn btn-inverse remove_fields' %>