config/routes.rb
EventStack::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register" }

  get "home/index"

  resources :users

  resources :majors

  resources :events do
    get :search, :on => :collection
  end

  root :to => 'home#index', as: 'home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventStack</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

    <div id="nav">
      <div id="title">
        <%= link_to home_path do %>
          <span>Event</span>Stack
        <% end %>
      </div>

      <% if user_signed_in? %>
        <ul id="buttons">
          <li class="separator"></li>
          <li> <%= link_to "Events", events_path %> </li>
          <li class="separator"></li>
          <li> <%= link_to "Users", users_path %> </li>
          <% if current_user.admin? %>
            <li class="separator"></li>
            <li> <%= link_to "Majors", majors_path %> </li>
          <% end %>
        </ul>
      <% end %>

      <ul id="login">
        <% if user_signed_in? %>
          <li> <%= link_to "Sign Out", destroy_user_session_path %> </li>
          <li class="separator"></li>
          <li> <%= link_to "#{current_user.first_name}", user_path(current_user.id) %> </li>
          <li id="hello_message"> Hi there, </li>
        <% else %>
          <li> <%= link_to "Want to join?", new_user_registration_path %> </li>
          <li class="separator"></li>
          <li> <%= link_to "Come on in!", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div>
    <div id="top_separator">
    </div>

<%= yield %>

</body>
</html>